#! /bin/bash

#this script creates new audio files divided in equal parts of a given amount
#it adds the remainder of samples to the last file

if [ $# -lt 2 ];
then
echo
echo "Give two parameters: file and number of slices. Like so:"
echo "LoopSlicer `pwd`/audio.wav 20"
echo
echo "A slice size of 1 gives a copy of the original audio file"
echo "2 divides the file in two equal parts"
echo "Program terminated"
exit
fi

FILE=$1
FILEDIR=`dirname $FILE`
BASENAME=`basename $FILE`
EXTENSION=".${BASENAME##*.}"
FILENAME="${BASENAME%.*}"
SLICES=$2
if [ ! -f $FILE ];
then
echo "Given file or directory doesn't exist"
echo "Example: `pwd`/audio.wav"
echo "Program terminated"
exit
fi

if [ $SLICES = 0 ];
then
echo "Zero slices were made"
exit
else
if [ $SLICES -lt 0 ];
then
echo "Can't make negative slices"
echo "Program terminated"
exit
fi
fi

SR=`soxi -r $FILE`
NOS=`soxi -s $FILE`
SS=$(($NOS/$SLICES))
REMAINDERSS=$(($NOS%$SLICES))

echo
echo "Creating $SLICES sliced files.."

for ((i=0; i<$SLICES;i++))
do
FILEOUT="$FILEDIR"/"$FILENAME"_$((i+1))"$EXTENSION"
echo "$FILEOUT"
if [ $i = $((SLICES-1)) ];
then
sox $FILE $FILEOUT trim $(($SS*$i))s $(($SS+REMAINDERSS))s
else
sox $FILE $FILEOUT trim $(($SS*$i))s "$SS"s
fi
done